# Generated by Django 2.2.8 on 2020-04-28 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admission_date', models.DateField(verbose_name='Qəbul ili')),
                ('admission_point', models.PositiveIntegerField(verbose_name='Qəbul Balı')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tələbə',
                'verbose_name_plural': 'Tələbələr',
            },
        ),
    ]
