# Generated by Django 2.2.8 on 2020-04-27 09:20

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Adı')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Qrup',
                'verbose_name_plural': 'Qruplar',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admission_date', models.DateField(verbose_name='Qəbul ili')),
                ('admission_point', models.PositiveIntegerField(verbose_name='Qəbul Balı')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='sms_app.Group')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tələbə',
                'verbose_name_plural': 'Tələbələr',
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=127)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Fənn',
                'verbose_name_plural': 'Fənnlər',
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='teacher', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Müəllim',
                'verbose_name_plural': 'Müəllimlər',
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=127, verbose_name='Taskın adı')),
                ('deadline', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sms_app.Subject')),
            ],
            options={
                'verbose_name': 'Sərbəst ',
                'verbose_name_plural': 'Tasks',
            },
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starts', models.DateTimeField(verbose_name='Başlama vaxtı')),
                ('ends', models.DateTimeField(verbose_name='Bitmə vaxtı')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sms_app.Subject')),
            ],
            options={
                'verbose_name': 'Cədvəl',
                'verbose_name_plural': 'Cədvəllər',
            },
        ),
        migrations.CreateModel(
            name='StudentTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sms_app.Student')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sms_app.Task')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sms_app.Teacher')),
            ],
            options={
                'verbose_name': 'StudentTask ',
                'verbose_name_plural': 'StudentTasks',
            },
        ),
        migrations.CreateModel(
            name='NotParticipating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField(default=datetime.datetime(2020, 4, 27, 9, 20, 8, 780010, tzinfo=utc), verbose_name='Day')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sms_app.Student')),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sms_app.Table')),
            ],
            options={
                'verbose_name': 'Qayıb',
                'verbose_name_plural': 'Qayıblar',
            },
        ),
        migrations.CreateModel(
            name='Dairy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point', models.PositiveSmallIntegerField(choices=[(1, 'One'), (2, 'Two'), (3, 'Three'), (4, 'Four'), (5, 'Five'), (6, 'Six'), (7, 'Seven'), (8, 'Eight'), (9, 'Nine'), (10, 'Ten')], verbose_name='Bal')),
                ('day', models.DateField(default=datetime.datetime(2020, 4, 27, 9, 20, 8, 778385, tzinfo=utc), verbose_name='Gün')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='sms_app.Student')),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sms_app.Table')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sms_app.Teacher')),
            ],
            options={
                'verbose_name': 'Gündəlik qiymət',
                'verbose_name_plural': 'Gündəlik qiymətlər',
            },
        ),
    ]
