# Generated by Django 2.2.8 on 2020-04-27 09:29

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('sms_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dairy',
            name='day',
            field=models.DateField(default=datetime.datetime(2020, 4, 27, 9, 29, 12, 782433, tzinfo=utc), verbose_name='Gün'),
        ),
        migrations.AlterField(
            model_name='notparticipating',
            name='day',
            field=models.DateField(default=datetime.datetime(2020, 4, 27, 9, 29, 12, 784029, tzinfo=utc), verbose_name='Day'),
        ),
    ]
