# Generated by Django 2.2.8 on 2020-04-28 10:57

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('sms_app', '0009_auto_20200428_1446'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notparticipating',
            name='day',
        ),
        migrations.AlterField(
            model_name='dairy',
            name='day',
            field=models.DateField(default=datetime.datetime(2020, 4, 28, 10, 57, 20, 911226, tzinfo=utc), verbose_name='Gün'),
        ),
    ]
