# Generated by Django 2.2.8 on 2020-04-28 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sms_app', '0010_auto_20200428_1457'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dairy',
            name='day',
        ),
    ]
