# Generated by Django 2.2.8 on 2020-04-30 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms_app', '0012_student_badges'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='badges',
            field=models.ManyToManyField(blank=True, null=True, related_name='students', to='dashboard_app.Badge'),
        ),
    ]
