# Generated by Django 2.2.8 on 2020-04-28 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_app', '0002_test'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test',
        ),
    ]
