# Generated by Django 2.2.8 on 2020-04-01 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_app', '0001_initial'),
        ('account_app', '0004_auto_20200401_1947'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='badges',
            field=models.ManyToManyField(blank=True, null=True, related_name='users', to='dashboard_app.Badge'),
        ),
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.IntegerField(choices=[(-1, 'unselected'), (0, 'male'), (1, 'female')], default=-1),
        ),
    ]
