# Generated by Django 2.2.8 on 2020-04-01 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_app', '0005_auto_20200401_2101'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='badges',
            field=models.ManyToManyField(blank=True, related_name='users', to='dashboard_app.Badge'),
        ),
    ]
