# Generated by Django 2.2.8 on 2020-04-20 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_app', '0006_auto_20200401_2110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(blank=True, height_field=100, null=True, upload_to='user/images', width_field=100),
        ),
    ]
